"%plugin.name.admin.base%_wholesale_ruleset":
  resource: |
    alias: skyboundtech.wholesale_ruleset
    section: admin
    #templates: "@SyliusAdmin\\Crud"
    templates: SkyBoundTechSyliusWholesaleSuitePlugin:CrudUi
    redirect: index
    grid: "%plugin.name.admin.base%_wholesale_ruleset"
    vars:
        all:
            header: "%plugin.name.base%.ui.wholesale_rulesets.header"
            subheader: "%plugin.name.base%.ui.wholesale_rulesets.subheader"
            templates:
              form: "@SkyBoundTechSyliusWholesaleSuitePlugin/CrudUi/_form.html.twig"
        index:
            icon: block layout
  type: sylius.resource
