sylius_grid:
  grids:
    "%plugin.name.admin.base%_wholesale_ruleset":
      driver:
        name: doctrine/orm
        options:
          class: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\WholesaleRuleset
      fields:
        name:
          type: string
          label: sylius.ui.name
        description:
          type: string
          label: sylius.ui.description
        enabled:
          type: twig
          label: sylius.ui.enabled
          options:
            template: "@SyliusUi/Grid/Field/enabled.html.twig"
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
        bulk:
          delete:
            type: delete
            label: sylius.ui.delete
            enabled: true
            position: 100
      filters:
        name:
          type: string
          label: sylius.ui.name
        isEnabled:
          type: boolean
          label: sylius.ui.enabled
#        type:
#          type: string
#          label: "%plugin.name.base%.ui.wholesale_rulesets.type"
#        scope:
#          type: string
#          label: "%plugin.name.base%.ui.wholesale_rulesets.scope"
##        scope:
##          type: string
##          label: "%plugin.name.base%.ui.wholesale_rulesets.scope"
##        rulesetTaxons:
##          type: entities
##          label: sylius.ui.taxonomy
##          form_options:
##            class: "%sylius.model.taxon.class%"
##          options:
##            field: "rulesetTaxons.id"
