imports:
  # SkyBound Tech Wholesale Suite

    # Import resources config
  - { resource: '@SkyBoundTechSyliusWholesaleSuitePlugin/Resources/config/resources.yml' }

    # Import grid config
  - { resource: '@SkyBoundTechSyliusWholesaleSuitePlugin/Resources/config/grids.yml' }
