sylius_taxonomy:
  resources:
    taxon:
      classes:
        model: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\Taxon

sylius_product:
  resources:
    product:
      classes:
        model: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\Product
#    product_variant:
#      classes:
#        model: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\ProductVariant
#        repository: SkyBoundTech\SyliusWholesaleSuitePlugin\Repository\ProductVariantRepository

# New resources
sylius_resource:
  resources:
    skyboundtech.wholesale_ruleset:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\WholesaleRuleset
        form: SkyBoundTech\SyliusWholesaleSuitePlugin\Form\Type\WholesaleRulesetType

    skyboundtech.wholesale_rule_quantity_step:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\WholesaleRuleQuantityStep
        interface: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\WholesaleRuleQuantityStepInterface
