sylius_resource:
  resources:
    skyboundtech.wholesale_ruleset:
      driver: doctrine/orm
      classes:
        model: SkyBoundTech\SyliusWholesaleSuitePlugin\Entity\WholesaleRuleset
        form: SkyBoundTech\SyliusWholesaleSuitePlugin\Form\Type\WholesaleRulesetCreateType
