"%plugin.name.admin.base%":
  resource: "@SkyBoundTechSyliusWholesaleSuitePlugin/Resources/config/routing/admin.yml"
  prefix: /admin

"%plugin.name.admin.base%_ajax":
  resource: "@SkyBoundTechSyliusWholesaleSuitePlugin/Resources/config/routing/admin/ajax.yml"
  prefix: /admin
