# Delete these routes and define your own shop routes here

sky_bound_tech_wholesale_suite_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: SkyBoundTechSyliusWholesaleSuitePlugin:Greeting:staticallyGreet
        name: ~

sky_bound_tech_wholesale_suite_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SkyBoundTechSyliusWholesaleSuitePlugin:Greeting:dynamicallyGreet
        name: ~
