skyboundtech_sylius_wholesale_suite_plugin_admin_ajax_product_variants_all:
  path: /search
  methods: [GET]
  defaults:
    _controller: sylius.controller.product_variant:indexAction
    _format: json
    _sylius:
      serialization_groups: [Autocomplete]
      permission: true
      repository:
        method: findAll
        arguments:
          phrase: $phrase
          locale: expr:service('sylius.context.locale').getLocaleCode()
          limit: 25
          productCode: $productCode
